# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: EmbeddingPolicy
    max_history: 5
    epochs: 200
    batch_size: 50
  - name: MemoizationPolicy
    max_history: 5
  - name: KerasPolicy
    max_history: 7
    epochs: 200
    batch_size: 80
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: "utter_action_default_fallback"



